config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :customers
  get 'dashboard/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
    has_many :Invoices
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  belongs_to :customer
  belongs_to :currency

  def invoice_status
    if status == 1
      return "Pending"
    elsif status == 2
      return "Overdue"
    elsif status == 3
      return "Paid"
    end
  end


 def self.payment_band(from, to)
 where("due_date <= '#{from}' and due_date >='#{to}'")
  end
def invoice_total_price (quantity=0,unit_price =0)
quantity * unit_price
 # invoice_quantity * invoice_unit_price
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers
  has_many :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone_number, :user_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  helper_method :arrears_amount_sum, :invoice_payment_band

  def index
    @invoices = Invoice.all
  end

  #Gets invoices whose due dates fall between the given to and from ranges. The range is converted first to actual times from the current date time
  def invoice_payment_band(from, to)
    from = Time.now.prev_day(from).strftime("%Y-%m-%d")
    to = Time.now.prev_day(to).strftime("%Y-%m-%d")
    records = Invoice.payment_band(from, to)
  end

  #Calculates the total amount for invoice records using field 'invoice_total_price'
  def arrears_amount_sum(records)
    total = 0
    records.each do |record|
      total = total + record.invoice_total_price
    end
    return total
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])

     respond_to do |format|
         format.html # show.html.erb
         format.js # show.js.erb
         format.json { render json: @invoice }
     end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:user_id, :customer_id, :currency_id, :due_date, :status, :invoice_description, :invoice_quantity, :invoice_unit_price, :invoice_total_price, :invoice_comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/customers/edit.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/navigation'%>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Editing <%= @customer.name %></h1>
      </div>
      <%= render 'layouts/notifications'%>

      <div class="table-responsive">
      <br/>
        <%= render 'form', customer: @customer %>
        <%= link_to 'Back', customers_path %>
      </div>
    </main>
  </div>
</div>

app/views/customers/index.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/navigation'%>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Customers</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <%= link_to new_customer_path do %>
                <button type="button" class="btn btn-sm btn-outline-secondary">+ New Customer</button>
            <%end%>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">Phone No</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.id %></td>
                <td><%= customer.name %></td>
                <td><%= customer.email %></td>
                <td><%= customer.phone_number %></td>
                <td>
                  <%= link_to customer do%>
                    <button class="btn btn-sm btn-primary">
                    View
                    </button>
                  <%end%>
                </td>
                <td>
                  <%= link_to edit_customer_path(customer) do%>
                    <button class="btn btn-sm btn-secondary">
                    Edit
                    </button>
                  <%end%>
                </td>
                <td>
                  <%= link_to customer, method: :delete, data: { confirm: 'Are you sure?' }  do%>
                    <button class="btn btn-sm btn-danger">
                    Delete
                    </button>
                  <%end%>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/customers/new.html.erb
<%= render 'layouts/header' %>
<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/navigation'%>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Customer</h1>
      </div>

      <div class="table-responsive">
      <br/>
        <%= render 'form', customer: @customer %>
        <%= link_to 'Back', customers_path %>
      </div>
    </main>
  </div>
</div>

app/views/customers/show.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/navigation'%>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"><%= @customer.name %></h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <%= link_to edit_customer_path(@customer) do%>
              <button type="button" class="btn btn-sm  btn-outline-primary">Edit</button>
            <%end%>
            <%= link_to @customer, method: :delete, data: { confirm: 'Are you sure?' }  do%>
              <button class="ml-2 btn btn-sm btn-danger">Delete</button>
            <%end%>
          </div>
        </div>
      </div>

      <div class="table-responsive">
          <p>
            <strong>Email:</strong>
            <%= @customer.email %>
          </p>

          <p>
            <strong>Phone number:</strong>
            <%= @customer.phone_number %>
          </p>

          <p>
            <strong>Created On:</strong>
            <%= @customer.created_at %>
          </p>

          <%= link_to 'Back', customers_path %>

      </div>
    </main>
  </div>
</div>

app/views/invoices/_invoice.html.erb
<div class="container-fluid">
    <div class="row">
        <%= render 'layouts/navigation'%>
            <p id="notice"><%= notice %></p>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <div class="container-fluid card" style= "width:fluid;">
                        <div class="row">
                            <div class="col-lg-6"></div>
                            <div class="col-lg-6">
                                <h1 class="font-weight-lighter py-1 px-3">INVOICE</h1>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col-lg-6">
                                <p class="mb-0">INVOICE TO</p>
                                <h5 class="mb-0"><b> <%= @invoice.customer.name %> </b></h5>
                                <p class="mb-0"><%= @invoice.customer.phone_number %></p>
                                <p class="mb-0"><%= @invoice.customer.email %></p>
                            </div>
                            <div class="col-lg-6">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <table>
                                            <tbody>
                                                <tr>
                                                    <td>Invoice No</td>
                                                    <td class="px-3">:</td>
                                                    <td><%= @invoice.id %></td>
                                                </tr>
                                                <tr>
                                                    <td>Due date</td>
                                                    <td class="px-3">:</td>
                                                    <td><%= @invoice.due_date %></td>
                                                </tr>
                                                <tr>
                                                    <td>Invoice Date</td>
                                                    <td class="px-3">:</td>
                                                    <td><%= @invoice.due_date %></td>
                                                </tr>
                                                <tr>
                                                    <td>Account No</td>
                                                    <td class="px-3">:</td>
                                                    <td>00000123</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">NO</th>
                                            <th scope="col">ITEM DESCREPTION</th>
                                            <th scope="col">QTY</th>
                                            <th scope="col">PRICE</th>
                                            <th scope="col">TOTAL</th>
                                            <th scope="col">CURRENCY</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>
                                                <b><%= @invoice.invoice_description %></b>
                                            </td>
                                            <td><%= @invoice.invoice_quantity %> </td>
                                            <td><%= @invoice.invoice_unit_price %></td>
                                            <td><%= @invoice.invoice_total_price %></td>
                                            <td><%= @invoice.currency.symbol %></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3"></td>
                                            <td><b>SUB Total</b></td>
                                            <td><b><%= @invoice.invoice_total_price %></b></td>
                                            <td colspan="3"></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3"></td>
                                            <td><b>TAX VAT 3%</b></td>
                                            <td><b>16200</b></td>
                                            <td colspan="3"></td>
                                        </tr>
                                        <tr style="background: #E6E4E7; color: #0099D5;">
                                            <td colspan="3"></td>
                                            <td><b>GRAND TOTAL</b></td>
                                            <td><b> <%= @invoice.invoice_total_price %> </b></td>
                                            <td colspan="3"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-lg-6">
                                <h5 class="ml-5">Invoice Comment</h5>
                                <p class="ml-5">
                                    <%= @invoice.invoice_comment %>
                                </p>
                            </div>
                            <div class="col-lg-3"></div>
                            <div class="col-lg-3 text-center">
                                <h3 class="signature">User signature</h3>
                                <p>User: <%= @invoice.user.first_name %></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <%= link_to 'Edit', edit_invoice_path(@invoice) %> |
                                <%= link_to 'Back', invoices_path %>
                            </div>
                        </div>
                    </div>

                </div>
            </main>
    </div>
</div>

app/views/invoices/edit.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
  <div class="row">
  <%= render 'layouts/navigation'%>

<p id="notice"><%= notice %></p>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="h2">Edit Invoice</h2>

  </div>

<%= render 'form', invoice: @invoice %>


<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
  <div class="row">
  <%= render 'layouts/navigation'%>

<p id="notice"><%= notice %></p>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="h2">Invoices</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <%= link_to new_invoice_path do %>
            <button type="button" class="btn btn-sm btn-outline-secondary">+ Create Invoice</button>
        <%end%>
      </div>

    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th scope="col">Customer</th>
      <th scope="col">Currency</th>
      <th scope="col">Due date</th>
      <th scope="col">Status</th>
      <th scope="col">Description</th>
      <th scope="col">Quantity</th>
      <th scope="col">Unit price</th>
      <th scope="col">Total price</th>
      <th scope="col">Comment</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.customer.name %></td>
        <td><%= invoice.currency.symbol %></td>
        <td><%= invoice.due_date %></td>
        <td><%= invoice.invoice_status %></td>
        <td><%= invoice.invoice_description %></td>
        <td><%= invoice.invoice_quantity %></td>
        <td><%= invoice.invoice_unit_price %></td>
        <td><%= invoice.invoice_total_price(invoice.invoice_quantity, invoice.invoice_unit_price) %></td>
        <td><%= invoice.invoice_comment %></td>

        <td><button class="btn btn-sm btn-outline-secondary">  <%= link_to 'Preview',invoice %> </button> </td>
        <td> <button class="btn btn-sm btn-outline-secondary">  <%= link_to 'Edit', edit_invoice_path(invoice) %> </button></td>
        <td> <button class="btn btn-sm btn-outline-secondary">  <%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' } %> </button></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

<br>
<%= render "layouts/modal" %>
<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/invoice.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
  <div class="row">
  <%= render 'layouts/navigation'%>

<p id="notice"><%= notice %></p>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="h2">Invoices#invoice</h2>

  </div>

</div>
</div>

app/views/invoices/new.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
  <div class="row">
  <%= render 'layouts/navigation'%>

<p id="notice"><%= notice %></p>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="h2">New Invoice</h2>

  </div>


<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<%= render 'layouts/header' %>

<div class="container-fluid">
    <div class="row">
        <%= render 'layouts/navigation'%>
            <p id="notice"><%= notice %></p>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <div class="container-fluid card" style= "width:fluid;">
                        <div class="row">
                            <div class="col-lg-10"></div>
                            <div class="col-lg-2">
                              <br>
                                <h4 class="font-weight-lighter py-1 px-3">INVOICE</h4>
                            </div>
                        </div>
                        <div class="row my-3">
                            <div class="col-lg-6">
                                <p class="mb-0">INVOICE TO</p>
                                <h5 class="mb-0"><b> <%= @invoice.customer.name %> </b></h5>
                                <p class="mb-0"><%= @invoice.customer.phone_number %></p>
                                <p class="mb-0"><%= @invoice.customer.email %></p>
                            </div>
                            <div class="col-lg-6">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <table>
                                            <tbody>
                                                <tr>
                                                    <td>Invoice No</td>
                                                    <td class="px-3">:</td>
                                                    <td><%= @invoice.id %></td>
                                                </tr>
                                                <tr>
                                                    <td>Due date</td>
                                                    <td class="px-3">:</td>
                                                    <td><%= @invoice.due_date %></td>
                                                </tr>
                                                <tr>
                                                    <td>Invoice Date</td>
                                                    <td class="px-3">:</td>
                                                    <td><%= @invoice.due_date %></td>
                                                </tr>
                                                <tr>
                                                    <td>Account No</td>
                                                    <td class="px-3">:</td>
                                                    <td>00000123</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">NO</th>
                                            <th scope="col">ITEM DESCREPTION</th>
                                            <th scope="col">QTY</th>
                                            <th scope="col">PRICE</th>
                                            <th scope="col">TOTAL</th>
                                            <th scope="col"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>
                                                <b><%= @invoice.invoice_description %></b>
                                            </td>
                                            <td><%= @invoice.invoice_quantity %> </td>
                                            <td><%= @invoice.invoice_unit_price %></td>
                                            <td><%= @invoice.invoice_total_price(@invoice.invoice_quantity,@invoice.invoice_unit_price) %></td>
                                            <td><%= @invoice.currency.symbol %></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3"></td>
                                            <td><b>SUB Total</b></td>
                                            <td><b><%= @invoice.invoice_total_price %></b></td>
                                            <td colspan="3"></td>
                                        </tr>


                                        <tr style="background: #E6E4E7; color: #0099D5;">
                                            <td colspan="3"></td>
                                            <td><b>GRAND TOTAL</b></td>
                                            <td><b> <%= @invoice.invoice_total_price(@invoice.invoice_quantity,@invoice.invoice_unit_price) %> </b></td>
                                            <td colspan="3"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-lg-6">
                                <h6 class="ml-5">Note: </h6>
                                <p class="ml-5">
                                    <%= @invoice.invoice_comment %>
                                </p>
                            </div>
                            <div class="col-lg-3"></div>
                            <div class="col-lg-3 text-center">
                                <h6 class="signature">Yours sincerely:</h6>
                                <p> <%= @invoice.user.first_name %>  <%= @invoice.user.last_name %></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <%= link_to 'Edit', edit_invoice_path(@invoice) %> |
                                <%= link_to 'Back', invoices_path %>
                            </div>
                        </div>
                    </div>

                </div>
            </main>
    </div>
</div>

app/views/invoices/show.js.erb
$modal = $('.modal'),
$modalBody = $('.modal .modal-body'),
$modalHeading = $('.modal .modal-heading');
$modalHeading.html("<%= @invoice.invoice_description%>");
$modalBody.html("<%= escape_javascript(render @invoice) %>");
$modal.modal();

app/views/layouts/_navigation.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to dashboard_index_path, class:"nav-link" do %>
                <i class="fa-solid fa-dashboard"></i> Dashboard
            <%end%>
        </li>
        <li class="nav-item">
            <%= link_to invoices_path, class:"nav-link" do %>
                <i class="fa-solid fa-chart-pie"></i> Invoices
            <%end%>
        </li>
        <li class="nav-item">
            <%= link_to customers_path, class:"nav-link" do %>
                <i class="fa-solid fa-chart-pie"></i> Customers
            <%end%>
        </li>
        <li class="nav-item">
            <%= link_to customers_path, class:"nav-link" do %>
                <i class="fa-solid fa-chart-pie"></i> Reports
            <%end%>
        </li>
        <li class="nav-item">
            <%= link_to customers_path, class:"nav-link" do %>
                <i class="fa-solid fa-chart-pie"></i> Currency
            <%end%>
        </li>
        <li class="nav-item">
            <%= link_to customers_path, class:"nav-link" do %>
                <i class="fa-solid fa-chart-pie"></i> Charts of Accounts
            <%end%>
        </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>Saved reports</span>
        <a class="link-secondary" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle"></span>
        </a>
    </h6>
    <ul class="nav flex-column mb-2">
        <li class="nav-item">
        <a class="nav-link" href="#">
            <span data-feather="file-text"></span>
            Current month
        </a>
        </li>
    </ul>
    </div>
</nav>